spring.application.name=back

# MySql
spring.datasource.url=jdbc:mysql://localhost:3306/running_app?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=dmsdbs22
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect